export const SKILLS_LIST: Record<string, string[]> = {
  'Frontend Development': [
    'React',
    'Vue.js',
    'Angular',
    'Next.js',
    'Nuxt.js',
    'TypeScript',
    'JavaScript',
    'HTML',
    'CSS',
    'Tailwind CSS',
    'Material UI',
    'Bootstrap',
    'Redux',
    'Vuex',
    'GraphQL',
    'REST API',
    'WebSocket',
    'Responsive Design',
    'Web Performance',
    'Web Accessibility',
  ],
  'Backend Development': [
    'Node.js',
    'Python',
    'Java',
    'C#',
    'PHP',
    'Ruby',
    'Go',
    'Rust',
    'Express.js',
    'Django',
    'Spring Boot',
    'Laravel',
    'Ruby on Rails',
    'ASP.NET',
    'GraphQL',
    'REST API',
    'WebSocket',
    'Microservices',
    'Docker',
    'Kubernetes',
  ],
  'Mobile Development': [
    'React Native',
    'Flutter',
    'iOS',
    'Android',
    'Swift',
    'Kotlin',
    'Java',
    'Objective-C',
    'Mobile UI/UX',
    'App Performance',
    'App Security',
    'Push Notifications',
    'Mobile Testing',
    'App Store Optimization',
  ],
  'Database': [
    'PostgreSQL',
    'MySQL',
    'MongoDB',
    'Redis',
    'Elasticsearch',
    'Firebase',
    'SQL',
    'NoSQL',
    'Database Design',
    'Data Modeling',
    'Database Optimization',
    'Database Security',
  ],
  'DevOps & Cloud': [
    'AWS',
    'Google Cloud',
    'Azure',
    'Docker',
    'Kubernetes',
    'CI/CD',
    'Jenkins',
    'GitLab CI',
    'GitHub Actions',
    'Terraform',
    'Ansible',
    'Linux',
    'Shell Scripting',
    'Monitoring',
    'Logging',
    'Security',
  ],
  'Testing': [
    'Unit Testing',
    'Integration Testing',
    'E2E Testing',
    'Jest',
    'Cypress',
    'Selenium',
    'Postman',
    'Test Automation',
    'Performance Testing',
    'Security Testing',
    'Manual Testing',
  ],
  'UI/UX Design': [
    'Figma',
    'Adobe XD',
    'Sketch',
    'User Research',
    'Wireframing',
    'Prototyping',
    'Visual Design',
    'Interaction Design',
    'Design Systems',
    'Accessibility',
    'User Testing',
  ],
  'Project Management': [
    'Agile',
    'Scrum',
    'Kanban',
    'JIRA',
    'Trello',
    'Project Planning',
    'Risk Management',
    'Team Leadership',
    'Communication',
    'Documentation',
  ],
  'Other': [
    'Git',
    'Machine Learning',
    'AI',
    'Data Science',
    'Blockchain',
    'IoT',
    'AR/VR',
    'Game Development',
    'Technical Writing',
    'SEO',
    'Analytics',
    'Digital Marketing',
  ],
}; 